version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions-toolkit:
        patterns:
          - "@actions/*"
      types:
        patterns:
          - "@types/*"
      dev-dependencies:
        dependency-type: development
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
